### ISSUE TITLE
Node.js Version?

### ISSUE THREAD

**Issue by progamer68** [kurisubrooks/midori#28]
I get this error while trying to run the bot (in [repl.it](https://replit.com)):
```
> npm start
[05:40:14 Process] Started
[05:40:14 Uncaught Exception] SyntaxError: Unexpected token '.'
Trace: /home/runner/azelia/core/CommandManager.js:151
    user.nickname = message.member?.displayName || message.author.username;
                                   ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/azelia/index.js:10:24)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Function.log (/home/runner/azelia/core/Util/Logger.js:30:22)
    at Function.error (/home/runner/azelia/core/Util/Logger.js:43:19)
    at process.<anonymous> (/home/runner/azelia/core/Util/Util.js:38:10)
    at process.emit (events.js:314:20)
    at process._fatalException (internal/process/execution.js:165:25)
```

**Comment by kurisubrooks** [comment]
Hi there, optional chaining is a feature that requires node.js 14 or higher.

**Comment by progamer68** [comment]
Is there a way to host this bot on repl.it?

**Comment by kurisubrooks** [comment]
Have no idea, you could just edit that line to work with whatever version of node you're running, but in general, you're not going to find any support for bots that will be run on any platforms that aren't dedicated servers/VPS' etc.
